@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Brunão da Massa",
  "email": "bruno@gmei.com",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "bruno@gmei.com",
  "password": "12345678"
}

###

# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Café com pão de queijo?",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}